#!/bin/bash
# E-Commerce FASE 1 - Quick Start Guide

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   E-COMMERCE FASE 1                            ║"
echo "║              ✅ Instalação Completa!                           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 STATUS DAS DEPENDÊNCIAS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Backend: Dependências instaladas (555 pacotes)"
echo "   - Framework: Express.js + TypeScript"
echo "   - ORM: Prisma"
echo "   - Auth: JWT + Bcrypt"
echo "   - Docs: Swagger/OpenAPI"
echo ""

echo "✅ Frontend: Dependências instaladas (711 pacotes)"
echo "   - Framework: Next.js 14"
echo "   - Styling: TailwindCSS"
echo "   - State: Context API"
echo "   - HTTP: Axios"
echo ""

echo "🔨 BUILDS:"
echo "━━━━━━━━━"
echo "✅ Backend TypeScript: Compilado com sucesso"
echo "✅ Frontend Next.js: Compilado com sucesso"
echo ""

echo "🚀 COMO TESTAR:"
echo "━━━━━━━━━━━━━━━"
echo ""

echo "OPÇÃO 1: Com Docker (Recomendado - Completo)"
echo "───────────────────────────────────────────"
echo "$ docker-compose up --build"
echo ""
echo "Endpoints:"
echo "  📱 Frontend:  http://localhost:3000"
echo "  🔌 Backend:   http://localhost:3001"
echo "  📚 Swagger:   http://localhost:3001/api-docs"
echo "  🗄️  PostgreSQL: localhost:5432"
echo ""

echo "OPÇÃO 2: Localmente (Requer PostgreSQL)"
echo "──────────────────────────────────────"
echo ""
echo "Terminal 1 - Backend:"
echo "  $ cd backend"
echo "  $ npx prisma migrate dev  # Setup DB"
echo "  $ npm run dev"
echo "  Acesso: http://localhost:3001"
echo ""
echo "Terminal 2 - Frontend:"
echo "  $ cd frontend"
echo "  $ npm run dev"
echo "  Acesso: http://localhost:3000"
echo ""

echo "🧪 TESTES:"
echo "─────────"
echo "Backend:"
echo "  $ cd backend && npm test"
echo ""
echo "Frontend:"
echo "  $ cd frontend && npm test"
echo ""

echo "📝 CREDENCIAIS DE TESTE (após criar):"
echo "────────────────────────────────────"
echo "Email: test@example.com"
echo "Senha: password123"
echo ""

echo "📊 ESTRUTURA DO PROJETO:"
echo "─────────────────────"
echo "."
echo "├── backend/"
echo "│   ├── src/          # Código TypeScript"
echo "│   ├── prisma/       # Migrations + schema"
echo "│   ├── tests/        # Testes Jest"
echo "│   └── Dockerfile"
echo "├── frontend/"
echo "│   ├── app/          # Páginas Next.js"
echo "│   ├── components/   # Componentes React"
echo "│   ├── contexts/     # Context API"
echo "│   ├── services/     # API client"
echo "│   └── Dockerfile"
echo "├── docker-compose.yml"
echo "└── README.md"
echo ""

echo "✨ FUNCIONALIDADES FASE 1:"
echo "──────────────────────"
echo "✅ Registro de usuário"
echo "✅ Login com JWT"
echo "✅ Listagem de produtos"
echo "✅ Detalhe do produto"
echo "✅ Categorias"
echo "✅ Admin: gerenciar produtos"
echo "✅ Swagger interativo"
echo "✅ Testes automatizados"
echo ""

echo "🎯 PRÓXIMAS FASES:"
echo "────────────────"
echo "📦 FASE 2: Carrinho + Pedidos"
echo "💳 FASE 3: Pagamento + Admin Dashboard"
echo "📊 FASE 4: Relatórios + LGPD"
echo "🐳 FASE 5: CI/CD + Kubernetes"
echo ""

echo "💡 DICA:"
echo "───────"
echo "Para testes rápidos locais sem PostgreSQL:"
echo "1. Instale PostgreSQL localmente"
echo "2. Configure DATABASE_URL no .env"
echo "3. Execute: npx prisma migrate dev"
echo "4. Rode: npm run dev (backend) e npm run dev (frontend)"
echo ""

echo "📚 DOCUMENTAÇÃO:"
echo "───────────────"
echo "  • README.md - Documentação completa"
echo "  • Swagger - http://localhost:3001/api-docs"
echo "  • Código - Bem estruturado e comentado"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║            Tudo pronto para começar! 🎉                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
